# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6e5618ee46dc387f51aceb3a8464fa483756d0c4df4c1f075670cdb394fcf8875df17b391933bc9ddedb942a91ccbeeec93eee14f782d71e0dd5b371df8a2de1

test:
  secret_key_base: 10eb987d181839b900b3b891280e14cbe2da3ab73cf3a71d0d6f2ec456d9977bee717407317647c004cbcae8cb1252dc48d93e619ee542c4731db17efb368535

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
